# Generated by Django 3.1 on 2020-08-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affairs', '0003_auto_20200828_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesOfReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория прихода',
                'verbose_name_plural': 'Категории прихода',
            },
        ),
        migrations.CreateModel(
            name='CategoriesOfSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расхода',
            },
        ),
        migrations.CreateModel(
            name='FinansyBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Баланс')),
                ('type', models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Банковский перевод')], default='CH', max_length=2, verbose_name='Вид движения средств')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('com', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('type', models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Банковский перевод')], default='CH', max_length=2, verbose_name='Вид движения средств')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finansy.categoriesofspending', verbose_name='Категория')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='affairs.affairs', verbose_name='Дело')),
                ('user_do', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Отвественный')),
            ],
            options={
                'verbose_name': 'Запись расхода',
                'verbose_name_plural': 'Записи расхода',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('com', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('type', models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Банковский перевод')], default='CH', max_length=2, verbose_name='Вид движения средств')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата прихода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finansy.categoriesofreceipt', verbose_name='Категория')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='affairs.affairs', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Запись прихода',
                'verbose_name_plural': 'Записи прихода',
            },
        ),
    ]
