# Generated by Django 3.1 on 2020-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finansybalance',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Вид движения средств'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Вид движения средств'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Вид движения средств'),
        ),
    ]
