# Generated by Django 3.1 on 2021-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansy', '0002_auto_20200828_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finansybalance',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Форма оплаты'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Форма оплаты'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='type',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BK', 'Расчетный счет')], default='CH', max_length=2, verbose_name='Форма оплаты'),
        ),
    ]
