# Generated by Django 3.1 on 2021-01-22 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
        ('finansy', '0003_auto_20210106_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='performers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель'),
        ),
    ]
