# Generated by Django 3.1 on 2021-08-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finansy', '0005_receipt_extra_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finansy.receipt', verbose_name='Бонус за приход ведущему'),
        ),
    ]
