# Generated by Django 3.1 on 2020-09-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformersDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номер договора')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Договор с исполнителем',
                'verbose_name_plural': 'Договора с исполнителем',
            },
        ),
    ]
