# Generated by Django 3.1 on 2020-09-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_performersdoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performersdoc',
            options={'verbose_name': 'Договор с исполнителями', 'verbose_name_plural': 'Договора с исполнителем'},
        ),
    ]
