# Generated by Django 3.1 on 2021-01-22 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='performers',
            name='adres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Прописка'),
        ),
        migrations.AddField(
            model_name='performers',
            name='birthday',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='performers',
            name='date_in',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=200, null=True, verbose_name='Дата принятия'),
        ),
        migrations.AddField(
            model_name='performers',
            name='date_out',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='performers',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='performers',
            name='pasby',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Паспорт выдан'),
        ),
        migrations.AddField(
            model_name='performers',
            name='pasdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='performers',
            name='paskod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код подразделения паспорта'),
        ),
        migrations.AddField(
            model_name='performers',
            name='pasno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер пасспорта'),
        ),
        migrations.AddField(
            model_name='performers',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
