# Generated by Django 3.1 on 2022-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('sale', models.IntegerField(verbose_name='Скидка в рублях')),
                ('linkpay', models.TextField(verbose_name='Ссылка на оплату')),
                ('aktive', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
