# Generated by Django 3.1 on 2022-09-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('set', models.TextField(blank=True, null=True, verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='linkpay',
            field=models.CharField(max_length=200, verbose_name='Ссылка на оплату'),
        ),
    ]
