# Generated by Django 3.1 on 2023-01-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220912_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konkurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('datain', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('dataout', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
        migrations.CreateModel(
            name='PlayerKonkurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('win', models.BooleanField(default=True, verbose_name='Выиграл или нет')),
                ('konkurs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.konkurs', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Участник конкурса',
                'verbose_name_plural': 'Участники конкурса',
            },
        ),
        migrations.CreateModel(
            name='ChatsForKonkurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamechat', models.TextField(blank=True, null=True, verbose_name='Паблик')),
                ('privyazka', models.BooleanField(default=True, verbose_name='Привязка')),
                ('useruser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.konkurs', verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Паблик',
                'verbose_name_plural': 'Паблики',
            },
        ),
    ]
