# Generated by Django 3.1 on 2020-08-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhereInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UR', 'Юридическое лицо'), ('FI', 'Физическое лицо')], default='FI', max_length=2)),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('dr', models.DateField(verbose_name='День рождения')),
                ('pasno', models.CharField(max_length=200, verbose_name='Серия и номер паспорта')),
                ('pasby', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('pasdate', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('paskod', models.CharField(max_length=200, verbose_name='Код подразделения паспорта')),
                ('address', models.CharField(max_length=200, verbose_name='Прописан')),
                ('tel', models.CharField(max_length=200, verbose_name='Телефон')),
                ('whereknow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.whereinfo', verbose_name='Источник информации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
