# Generated by Django 3.1 on 2020-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Прописан'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dr',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasby',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='paskod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код подразделения паспорта'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
