# Generated by Django 3.1 on 2021-05-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200909_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='type',
            field=models.CharField(choices=[('UR', 'Юридическое лицо'), ('FI', 'Физическое лицо')], default='FI', max_length=2, verbose_name='Тип'),
        ),
    ]
