# Generated by Django 3.1 on 2023-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210519_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='adresfiktiv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фиктивный адрес для договора и справок'),
        ),
        migrations.AddField(
            model_name='customers',
            name='cityfiktiv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фиктивный город для договора и справок'),
        ),
        migrations.AddField(
            model_name='customers',
            name='pol',
            field=models.CharField(blank=True, choices=[('UR', 'Мужской'), ('FI', 'Женский')], max_length=2, null=True, verbose_name='Пол'),
        ),
    ]
