# Generated by Django 3.1 on 2023-01-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20230119_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='spravkaspivarvipis',
            name='krat',
            field=models.FloatField(blank=True, null=True, verbose_name='Кратность'),
        ),
        migrations.AddField(
            model_name='spravkaspivarvipis',
            name='maxprise',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='spravkaspivarvipis',
            name='minprise',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
    ]
