# Generated by Django 3.1 on 2023-01-23 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_auto_20230119_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='byuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил в программу'),
        ),
        migrations.AddField(
            model_name='customers',
            name='paswhat',
            field=models.CharField(default='Паспорт РФ', max_length=200, verbose_name='Удостоверение личности (прим: Паспорт РФ'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='adresfiktiv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фиктивный адрес для договоров и справок'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cityfiktiv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фиктивный город для договоров и справок'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dr',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasby',
            field=models.CharField(max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasdate',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pasno',
            field=models.CharField(max_length=200, verbose_name='Серия и номер документа'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pol',
            field=models.CharField(choices=[('UR', 'Мужской'), ('FI', 'Женский')], max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='whereknow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.whereinfo', verbose_name='Источник информации'),
        ),
    ]
