# Generated by Django 3.1 on 2023-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20230123_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TildaInSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('summa', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('incrm', models.BooleanField(blank=True, max_length=200, null=True, verbose_name='Есть ли в црм')),
            ],
            options={
                'verbose_name': 'Оплата через тильду',
                'verbose_name_plural': 'Оплаты через тильду',
            },
        ),
    ]
