# Generated by Django 3.1 on 2023-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_tildainsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='iin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИИН'),
        ),
    ]
