# Generated by Django 3.1 on 2020-08-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дела')),
                ('deal', models.CharField(max_length=200, verbose_name='Ссылка на сделку Битрикс')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('prise', models.FloatField(verbose_name='Цена')),
                ('priseperformer', models.FloatField(verbose_name='Вознаграждение для исполнителя')),
                ('prisealready', models.FloatField(default=0, verbose_name='Оплачено клиентом')),
                ('priseperformeralready', models.FloatField(default=0, verbose_name='Выплачено исполнителю')),
                ('customers', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers', verbose_name='Клиент')),
                ('performer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
    ]
