# Generated by Django 3.1 on 2020-08-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
        ('affairs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairs',
            name='color',
        ),
        migrations.AddField(
            model_name='affairs',
            name='jobcategories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.jobcategories', verbose_name='Исполнитель'),
        ),
    ]
