# Generated by Django 3.1 on 2020-08-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
        ('affairs', '0002_auto_20200827_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='jobcategories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.jobcategories', verbose_name='Вид'),
        ),
    ]
