# Generated by Django 3.1 on 2020-09-03 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_auto_20200828_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='date_in',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала сделки'),
        ),
        migrations.AddField(
            model_name='affairs',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания сделки'),
        ),
        migrations.AddField(
            model_name='affairs',
            name='deal_status',
            field=models.CharField(choices=[('ON', 'В процессе'), ('WI', 'Заверешено (Удачно)'), ('LO', 'Заверешено (Неудачно)')], default='ON', max_length=2, verbose_name='Статус Дела'),
        ),
    ]
