# Generated by Django 3.1 on 2020-09-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_auto_20200903_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='prise_status',
            field=models.CharField(choices=[('NO', 'Не оплаченно'), ('YE', 'Оплаченно')], default='NO', max_length=2, verbose_name='Статус Оплаты'),
        ),
    ]
