# Generated by Django 3.1 on 2020-09-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_performersdoc'),
        ('affairs', '0005_affairs_prise_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='jobcategories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.jobcategories', verbose_name='Категория дела'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Номер договора'),
        ),
    ]
