# Generated by Django 3.1 on 2020-09-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
        ('affairs', '0006_auto_20200916_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='performer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='priseperformer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вознаграждение для исполнителя'),
        ),
    ]
