# Generated by Django 3.1 on 2020-12-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0007_auto_20200922_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAffairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номер доп.договора')),
                ('sum', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('comment', models.CharField(max_length=5000, verbose_name='Комментарий')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('affairs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affairs.affairs', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Дополнительное дело',
                'verbose_name_plural': 'Дополнительные дела',
            },
        ),
    ]
