# Generated by Django 3.1 on 2020-12-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
        ('affairs', '0008_extraaffairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairs',
            name='performer',
        ),
        migrations.AddField(
            model_name='affairs',
            name='performer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='performers.Performers', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='extraaffairs',
            name='affairs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affairs.affairs', verbose_name='Дело'),
        ),
    ]
