# Generated by Django 3.1 on 2020-12-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
        ('affairs', '0010_extraperformer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraperformer',
            name='affairs',
        ),
        migrations.RemoveField(
            model_name='extraperformer',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='affairs',
            name='performer',
        ),
        migrations.AddField(
            model_name='affairs',
            name='performer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель'),
        ),
        migrations.DeleteModel(
            name='ExtraAffairs',
        ),
        migrations.DeleteModel(
            name='ExtraPerformer',
        ),
    ]
