# Generated by Django 3.1 on 2020-12-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_auto_20200922_1754'),
        ('affairs', '0011_auto_20201222_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairs',
            name='performer',
        ),
        migrations.AddField(
            model_name='affairs',
            name='performer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='performers.Performers', verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='ExtraPerfomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('affairs', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='affairs.affairs', verbose_name='Номер дела')),
                ('performer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performers', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Промежуток',
                'verbose_name_plural': 'Промежуток',
            },
        ),
        migrations.CreateModel(
            name='ExtraAffairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номер договора')),
                ('sum', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('comment', models.TextField(max_length=5000, verbose_name='Коментарий')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('affairs', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='affairs.affairs', verbose_name='Номер дела')),
            ],
            options={
                'verbose_name': 'Дополнительное дело',
                'verbose_name_plural': 'Дополнительные дела',
            },
        ),
    ]
