# Generated by Django 3.1 on 2021-05-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0015_auto_20210519_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairs',
            name='priseperformer',
        ),
        migrations.RemoveField(
            model_name='affairs',
            name='priseperformeralready',
        ),
    ]
