# Generated by Django 3.1 on 2021-06-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0016_auto_20210519_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='com',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по делу'),
        ),
        migrations.AddField(
            model_name='extraaffairs',
            name='deal',
            field=models.CharField(default='Нет', max_length=200, verbose_name='Ссылка на сделку Битрикс'),
        ),
    ]
