# Generated by Django 3.1 on 2021-06-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0018_auto_20210602_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraperfomer',
            name='extraaffairs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='affairs.extraaffairs', verbose_name='Номер доп.дела'),
        ),
    ]
