# Generated by Django 3.1 on 2021-06-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_auto_20210122_1341'),
        ('affairs', '0021_affairs_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='performers.performers', verbose_name='Ведет дело'),
        ),
    ]
